### ISSUE TITLE
could logo links be just to /

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/harrow-woodcraft-new-members#29]
to avoid hard coding the particular url of the site

**Comment by javpet** [comment]
Oh yeah, good call, I was hardcoding the URL!

**Comment by tansaku** [comment]
no worries @javpet - @Linducya @smarbaf and I were working on the same feature as part of the webdev mob and the idea came to us - one of the great things about the group mind in a mob :-) 

Shame you can't make our mobbing sessions ...

**Comment by javpet** [comment]
Oh yeah definitely a pity, just have to deal with this stupid thing called 'earning money' :(

**Comment by tansaku** [comment]
@javpet maybe someday we can help you with that :-)
