### ISSUE TITLE
Changing Harrow Woodcraft logo to svg

### ISSUE THREAD

**Issue by javpet** [AgileVentures/harrow-woodcraft-new-members#5]
## Problem statement
The page is currently using a PNG file from other resources than Harrow Woodcraft, so it would be beneficial to get the official logo, and implement in crisp SVG so it doesn't matter of scaling, and later we might even animate it.

## Setup requirement
- @tansaku to get Harrow Woodcraft logo in SVG or other vector format

## Code requirement
- Changing the existing PNG logo instance to SVG

**Comment by tansaku** [comment]
anyone with illustrator or photoshop could make the necessary files - my trials are expired at the moment ... :-(

Or we could ask the client ...

**Comment by javpet** [comment]
Sure I’ll pick this up. Do you have already the raw vector illustrator
file @tansaku from the client?

**Comment by tansaku** [comment]
@javpet I do - I'll send to you on slack

**Comment by javpet** [comment]
I've checked the materials @tansaku but inside the PSD the logo is not a vector smart object, or something we can extract to make nicer SVG out of it, so if you could ask the client to send us maybe just the logo?

**Comment by tansaku** [comment]
@javpet have requested

**Comment by tansaku** [comment]
https://www.dropbox.com/s/in861u0zjd27ler/Single%20Colour%20Woodcraft%20Folk%20Logo.eps?dl=0

https://www.dropbox.com/s/u42evup90rs1k79/Multiple%20Colours%20Woodcraft%20Folk%20Logo%20%282%29.eps?dl=0
